apiVersion: v1
baseDomain: xxx-dev.iz.xxx.xxx
credentialsMode: Manual 
controlPlane:   
  hyperthreading: Enabled 
  name: master
  platform:
    aws:
      zones:
      - ap-southeast-1a
      - ap-southeast-1b
      - ap-southeast-1c
      rootVolume:
        iops: 4000
        size: 120
        type: io1 
      type: m5.xlarge
  replicas: 3
compute: 
- hyperthreading: Enabled 
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 120
        type: io1 
      type: c5.2xlarge
      zones:
      - ap-southeast-1a
      - ap-southeast-1b
      - ap-southeast-1c
  replicas: 3
metadata:
  name: TO-BE-DECIDED
networking:
  clusterNetwork:
  - cidr: 172.31.64.0/18
    hostPrefix: 23
  machineNetwork:
  - cidr: 100.120.105.0/24
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.32.144.0/20
platform:
  aws:
    region: ap-southeast-1 
    userTags:
      adminContact: <TO_BE_FILLED>
      costCenter: <TO_BE_FILLED>
    subnets: 
    - subnet-1
    - subnet-2
    - subnet-3
    amiID: ami-<TO_BE_FILLED>
    serviceEndpoints: 
      - name: ec2
        url: https://ec2.ap-southeast-1.amazonaws.com
    hostedZone: <TO_BE_FILLED> Z3URY6TWQ91KVV 
fips: false 
sshKey: ssh-ed25519 AAAA... 
pullSecret: '{"auths":{"<local_registry>": {"auth": "<credentials>","email": "you@example.com"}}}' 
additionalTrustBundle: | 
    -----BEGIN CERTIFICATE-----
    <MY_TRUSTED_CA_CERT>
    -----END CERTIFICATE-----
imageContentSources: 
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - <local_registry>/<local_repository_name>/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
