apiVersion: v1
stringData:
  credentials: |-
    [default]
    sts_regional_endpoints = regional
    role_arn = arn:aws:iam::xxxxxxxx:role/yyyyxxx
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
kind: Secret
metadata:
  name: mas-etcd-backup
  namespace: mas-etcd-backup
type: Opaque
