apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: mas-routing
  namespace: ns2
spec:
  route:
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'null'
    route:
    - receiver: 'aws-ses'
      matchers:
      - app = 'prometheus-example-app'
  receivers:
    - name: 'null'
    - name: 'aws-ses'
      email_configs:
      - to: "xxxx@xxx.sg"
        from: "xxxx@xxx.sg"
        smarthost: "email-smtp.ap-southeast-1.amazonaws.com:587"
        auth_username: "xxxx"
        auth_password: "xxxx"
        authIdentity: "xxxxx@xxx.sg"
        require_tls: true
