apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: monitoring-stack-alerts 
  namespace: ns1 
spec:
  groups:
  - name: general.rules
    rules:
    - alert: TargetDown 
      annotations:
        message: '{{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service
          }} targets in {{ $labels.namespace }} namespace are down.' 
      expr: 100 * (count(up == 0) BY (job, namespace, service) / count(up) BY (job,
        namespace, service)) > 10
      for: 10m 
      labels:
        severity: warning 
    - alert: ApproachingEnforcedSamplesLimit 
      annotations:
        message: '{{ $labels.container }} container of the {{ $labels.pod }} pod in the {{ $labels.namespace }} namespace consumes {{ $value | humanizePercentage }} of the samples limit budget.' 
      expr: scrape_samples_scraped/50000 > 0.8 
      for: 10m 
      labels:
        severity: warning
