apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mas-team1
  namespace: ns2
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
    prometheus: k8s
    role: alert-rules
spec:
  groups:
  - name: mas-team1-rules
    rules:
    # Alert for team1 application high threshold for >1 minutes.
    # expr: count(http_request_duration_seconds_count{job="prometheus-example-app", code="200"}) > 20
    - alert: ns2AppsCount
      expr: http_request_duration_seconds_count > 45
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: High http count

    # Alert for any instance that is unreachable for >5 minutes.
    - alert: InstanceDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Instance {{ $labels.instance }} down"
        description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."
