apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  audit:
    profile: Default
    customRules:                        
    - group: system:unauthenticated
      profile: AllRequestBodies
  encryption:
    type: aescbc 
