apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
  name: <infrastructure_id>-infra-<zone> 
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
      machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra-<zone> 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: <infrastructure_id> 
        machine.openshift.io/cluster-api-machine-role: <infra> 
        machine.openshift.io/cluster-api-machine-type: <infra> 
        machine.openshift.io/cluster-api-machineset: <infrastructure_id>-infra-<zone> 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      taints: 
        - key: "node-role.kubernetes.io/infra"
          operator: "Exist"
          effect: "NoExecute"
      providerSpec:
        value:
          ami:
            id: ami-046fe691f52a953f9 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: <infrastructure_id>-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-east-1a
            region: us-east-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - <infrastructure_id>-worker-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - <infrastructure_id>-private-us-east-1a 
          tags:
            - name: kubernetes.io/cluster/<infrastructure_id> 
              value: owned
          userDataSecret:
            name: worker-user-data
