apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: mas-application-A
  namespace: openshift-ingress-operator
spec:
  domain: xx.yy.zz
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
