apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: etcd-backup-cred
  namespace: mas-etcd-backup
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - s3:ListBucket
      effect: Allow
      resource: "arn:aws:s3:::jeretan-rosa"
    - action:
      - s3:PutObject
      - s3:GetObject
      - s3:DeleteObject
      effect: Allow
      resource: "arn:aws:s3:::jeretan-rosa/*"
  secretRef:
    name: etcd-backup-cred
    namespace: mas-etcd-backup
  serviceAccountNames:
  - mas-backup-operator
