apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: etcd-backup-cred
  namespace: mas-etcd-backup
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - s3:*
      - iam:PassRole
      effect: Allow
      resource: "arn:aws:s3:::<your-bucket>"
  secretRef:
    name: etcd-backup-cred
    namespace: mas-etcd-backup
  serviceAccountNames:
  - mas-backup-operator
