apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: etcd-backup-cred
  namespace: mas-etcd-backup
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: AWSProviderSpec
    statementEntries:
    - action:
      - s3:CreateBucket
      - s3:DeleteBucket
      - s3:GetAccelerateConfiguration
      - s3:GetBucketAcl
      - s3:GetBucketCors
      - s3:GetBucketLocation
      - s3:GetBucketLogging
      - s3:GetBucketObjectLockConfiguration
      - s3:GetBucketRequestPayment
      - s3:GetBucketTagging
      - s3:GetBucketVersioning
      - s3:GetBucketWebsite
      - s3:GetEncryptionConfiguration
      - s3:GetLifecycleConfiguration
      - s3:GetReplicationConfiguration
      - s3:ListBucket
      - s3:PutBucketAcl
      - s3:PutBucketTagging
      - s3:PutEncryptionConfiguration
      - s3:DeleteObject
      - s3:GetObject
      - s3:GetObjectAcl
      - s3:GetObjectTagging
      - s3:GetObjectVersion
      - s3:PutObject
      - s3:PutObjectAcl
      - s3:PutObjectTagging
      - s3:DeleteObject
      - s3:ListBucketVersions
      - s3:PutBucketPublicAccessBlock
      - s3:GetBucketPublicAccessBlock
      - s3:PutLifecycleConfiguration
      - s3:ListBucketMultipartUploads
      - s3:AbortMultipartUpload
      effect: Allow
      resource: "arn:aws:s3:::<your-bucket>"
  secretRef:
    name: etcd-backup-cred
    namespace: mas-etcd-backup
  serviceAccountNames:
  - mas-backup-operator
